---
- hosts: localhost
  connection: local
  become: true

  roles:
    - role: updates
      tags: [setup, updates]
    - role: storage
      tags: [setup, storage]
    - role: docker
      tags: [setup, docker]
    - role: immich
      tags: [media, photos]
