---
- hosts: localhost
  connection: local
  become: true

  roles:
    - role: storage
      tags: [setup]
    - role: docker
      tags: [setup]
    - role: immich
      tags: [media, photos]
